name: Zip and Upload to S3

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get version from file
        id: get-version
        run: |
          echo "VERSION=$(jq -r '.version' manifest.json)" >> "$GITHUB_ENV"

      - name: Get version from tag
        id: tag_name
        run: |
          echo "CURR_VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
          
      - name: Verify CURR_VERSION
        run: |
          echo "CURR_VERSION is ${{ env.CURR_VERSION }}"

  create-release:
    runs-on: ubuntu-latest
    needs: get-latest-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURR_VERSION }}
          release_name: Release ${{ env.CURR_VERSION }}
          prerelease: false
          draft: false
          body: |
            This is the release notes for version ${{ env.CURR_VERSION }}.
            You can add more details here.

  build-and-upload:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies required for your script (if any)
          # For example:
          # npm install

      - name: Zip files
        run: |
          # Run a script to create the zip file
          # Example: zip -r myfiles.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./  # Directory containing the zip file
          DEST_DIR: /  # Destination directory in S3 (root directory)
