name: Zip and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release version
        id: get_latest_release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const latestRelease = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(latestRelease.data.tag_name);
            const currentVersion = latestRelease.data.tag_name;
            const versionComponents = currentVersion.split('.');
            const majorVersion = parseInt(versionComponents[0]);
            const minorVersion = parseInt(versionComponents[1]);
            const patchVersion = parseInt(versionComponents[2]);
            const nextVersion = `${majorVersion}.${minorVersion}.${patchVersion + 1}`;
            console.log(nextVersion);
            core.setOutput('next_version', nextVersion);

  create-release:
    runs-on: ubuntu-latest
    needs: get-latest-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-latest-release.outputs.next_version }}
          release_name: Release ${{ steps.get-latest-release.outputs.next_version }}
          prerelease: false
          draft: false
          body: |
            This is the release notes for version ${{ steps.get-latest-release.outputs.next_version }}.
            You can add more details here.

  build-and-upload:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      # Add your steps for building and uploading to S3 here
