name: Zip and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps for creating a release...
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with your version number
          release_name: Release v1.0.0  # Replace with your release name
          prerelease: false
          draft: false
          body: |
            This is the release notes for version 1.0.0.
            You can add more details here.

  build-and-upload:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies required for your script (if any)
          # For example:
          # npm install

      - name: Zip files
        run: |
          # Run a script to create the zip file
          # Example: zip -r myfiles.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./  # Directory containing the zip file
          DEST_DIR: /  # Destination directory in S3 (root directory)
