name: Zip and Upload to S3

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  get-latest-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get version from file
        id: get-version
        run: |
            VERSION=$(jq -r '.version' manifest.json)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Use VERSION
        run: |
            echo "Version is ${{ env.VERSION }}"

      - name: Extract latest changes from CHANGELOG.md
        id: extract-changes
        run: |
            # Use awk to find the latest version
            latest_version=$(awk '/^## \[/ {print $2; exit}' CHANGELOG.md)

            # Extract the changes for the latest version
            changes=$(sed -n "/^## \[$latest_version\]/,/^## \[/p" CHANGELOG.md | sed '$d')

            # Set the changes as an output
            echo "Changes are ${{changes}}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        with:
          tag_name: ${{ env.VERSION }} # Use the environment variable
          release_name: Release ${{ env.VERSION }}
          prerelease: false
          draft: false
          body: ${{ steps.extract-changes.outputs.changes }} # Use the extracted changes as the body

  build-and-upload:
    runs-on: ubuntu-latest
    needs: get-latest-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies required for your script (if any)
          # For example:
          # npm install

      - name: Zip files
        run: |
          # Run a script to create the zip file
          # Example: zip -r myfiles.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./ # Directory containing the zip file
          DEST_DIR: /    # Destination directory in S3 (root directory)
